# Tab indented YAML 3
app:
	name: "Test App 3"
	version: "1.3.0"
	settings:
		debug: false
		log_level: info
		features:
			- feature1
			- feature2
			- feature3
database:
	host: db-3.example.com
	port: 5432
	credentials:
		username: user3
		password: pass3
